### ISSUE TITLE
Re-enable tests that fail with 'Illegal character escape code'

### ISSUE THREAD

**Issue by thomashoneyman** [purescript-contrib/purescript-unicode#28]
In #26 we updated to a newer version of the PureScript compiler, which is stricter about valid escape codes. This causes some of our tests to no longer compile. An example error message:

```
[1/1 ErrorParsingModule] test/Test/Data/Char/Unicode.purs:78:27

  78          generalCategory '\31' `shouldEqual` Just Control
                                ^
  Unable to parse module:
  Illegal character escape code
```

In #26 the affected tests were disabled with a comment `-- DISABLED`, but we should re-enable these tests as soon as it's clear how to include these characters in the code.

**Comment by cdepillabout** [comment]
Here's the actual commit from #26 disabling these tests: https://github.com/purescript-contrib/purescript-unicode/pull/26/commits/ac0ecf2ac2f20c73940b327dafeb67556db119b5

**Comment by JordanMartinez** [comment]
Could these be obtained by using `fromCodePoint` or something like that?

**Comment by garyb** [comment]
Could define the value in the FFI perhaps?

**Comment by hdgarrood** [comment]
Just for future reference, 0.13.0 isn't really "stricter" about character escape codes, it's just got a different syntax. Every possible string can be written with character escape codes both pre- and post-0.13; you don't ever need to use the FFI or use fromCodePoint or anything like that. From the 0.13.0 release notes:

> The only escapes accepted in string literals are `\n\r\t\'\"\\`, `\x[0-9a-fA-F]{1,6}` (unicode hex escape), and `\[\r\n ]+\` (gap escapes). We had inherited a vast zoo of escape codes from the Parsec Haskell Language parser. We decided to minimize what we support, and only add things back if there is significant demand.

Before 0.13.0, `'\31'` meant a char whose decimal code point value was 31. After 0.13.0, we only support hex escapes, so all you need to do is convert 31 to hex (which is 1F) and then write it with a hex escape code, so that's `'\x1F'`.
